strongloop/strong-mesh-models

models/action.json, models/profile-data.js, models/profile-data.json, models/service-instance.js, models/service-instance.json, models/service-metric.json, models/service-process.js, models/service-process.json, models/service.js, models/service.json, package.json
Ensures that there are no ID conflicts when collecting data from multiple PMs and processing them in mesh API. Also allows for consistent access to models related to the Instance.
* Change Action, ProfileData, ServiceProcess models to have string ID
* Create String IDs instead of using autogenerated numeric IDs
* Make foreign keys to ServiceInsance consistent (serviceInstanceId)
* Add relation between ServiceProcess and ProfileData
* Add relation between ServiceMetric and ServiceInstance
=> Use string IDs for models maintained in PM memory

models/express-usage-record.json, test/app/model-config.json
When the supervised express-base application has strong-express-metrics configured, strong-agent and strong-supervisor will forward usage records which will be stored in the ExpressUsageRecord model.
Connect to strongloop/strong-pm#125
=> Add support for Express Usage records

common/models/service.js, common/models/service.json, server/models/server-service.js, test/test-service-create-destroy.js, test/test-service-env.js
Adds PUT and DELETE handlers for /Services/:id/env/:name to set/unset individual environment variables so that API callers don't need to fetch/modify/put the entire environment object just to make a single change.
Based on #19, so most of the commits are from there.
Connected to strongloop/strong-pm#48
=> Add Service methods for setting/unsetting environment variables

server/models/express-usage-record.js, test/test-notification-model-updates.js
Record coming from strong-express-metric module use `timestamp` instead
of `timeStamp`.
=> Fix recording of express metric timestamp

bin/sl-meshctl.js, common/models/service-instance.json, server/models/service-instance.js
Only the set-size command was actually changing a running instance's
size. Updates to the size were being notified as onInstanceUpdate to pm,
but it wouldn't apply them to the running instance (doing so requires
sending a set-size command).
Now, if you don't want persistence, a set-size command is sent, which is
non-persistent.
If you do want persistence, the model is updated, that update goes to
pm, which then updates both the instance sl-run CLI options AND sends a
set-size command to a running instance (if size has changed). Because of
this, the persistent branch that sends set-size is no longer necessary.
Also, some effort was being made to capture non-numeric values for cpus,
and turn them into some default value. This code is confusing and
unused, its now gone. The size can be set …
=> server: persist instance.cpus to trigger resize

bin/sl-meshctl.js, test/meshctl-helper.js
Node 0.12 and iojs, when no bind address is specified, give null as
the listening address instead of '0.0.0.0', so as a quick fix we'll
just do that substitution ourselves.
Connect to strongloop-internal/scrum-nodeops#542
=> fix null listening addresses in meshctl status

bin/sl-meshctl.js
`slc ctl -C http://no-such.com` was triggering the message splitting in
the middle of the host name, so split only on '. ', which is what
loopback uses for long errors.
=> meshctl: fix message splitting

bin/sl-meshctl.js, client/client.js, test/test-client-version-match.js, test/test-client-version-mismatch.js
Checks whether the remote API version is major-compatible with the
client's API version.
connected to strongloop-internal/scrum-nodeops#544
connected to strongloop-internal/scrum-nodeops#545
=> client: implement checkRemoteApiSemver()

bin/sl-meshctl.txt
Identify more clearly the scope of commands, and don't use ID...
services, executors, processes and workers all have IDs, its too
confusing.
connected to strongloop-internal/scrum-nodeops#508
=> meshctl: clarify usage message

common/models/service.js, server/models/server-service.js, test/test-meshctl-env.js
Back ported from master/6.x
I'd like to release this as 5.1.0 so that strongloop/strong-arc#1226 can be simplified to use the same API it will use when strong-mesh-client is upgraded to use strong-mesh-models@6.
/cc @jtary
=> Add setEnvs remote method to Service model

package.json, server/models/service-process.js, test/test-deploy-endpoints.js, test/test-notification-model-updates.js, test/test-service-create-destroy.js
When upserting a ServiceProcess instance for a `fork` event, clear the `stopReason` and `stopTime` so that they are properly marked as running if they were previously marked as dead.
Also some small tweaks to some tests to work with an upgrade of tap.
=> Properly revive processes on fork

server/server.js, test/test-trace-client-api.js, test/test-trace-disabled-client-api.js
strong-supervisor now emits the trace object record as a string, as a
performance optimization.
Refs: https://github.com/strongloop/strong-supervisor/pull/129
R=@sam-github
=> trace-object: records are stringified now

client/client.js, client/models/server-service.js, package.json, test/test-client-version-match.js, test/test-meshctl-version.js
The package version is the semver for the js API used by packages that
require strong-mesh-models, the apiVersion is for the REST API.
connected to strongloop-internal/scrum-nodeops#610
=> Distinguish REST API and js API version

bin/sl-meshctl.js
Attempt to find source of this difficult to reproduce bug:
strong-mesh-models/node_modules/text-table/index.js:59
return m ? m.index + 1 : c.length;
^
TypeError: Cannot read property 'length' of null
at dotindex (strong-mesh-models/node_modules/text-table/index.js:59:31)
at strong-mesh-models/node_modules/text-table/index.js:11:21
at Array.forEach (native)
at forEach (strong-mesh-models/node_modules/text-table/index.js:73:31)
at strong-mesh-models/node_modules/text-table/index.js:10:9
at Array.reduce (native)
at reduce (strong-mesh-models/node_modules/text-table/index.js:63:30)
at module.exports (strong-mesh-models/node_modules/text-table/index.js:9:20)
at strong-mesh-models/bin/sl-meshctl.js:214:35
at strong-mesh-models/client/models/server-service.js:100:9
=> meshctl: assert instance is well-formed

bin/sl-meshctl.js
Asserts added in 94ef1e4 in #65 broke pmctl when accessing an instance
with cluster size of 0, which is the initial state for apps that are
dockerized by strong-pm.
This was causing strong-pm's pmctl tests fail for me.
=> fix over aggressive assert

bin/sl-meshctl.js, bin/sl-meshctl.txt, package.json
connected to strongloop-internal/scrum-nodeops#444
=> Use only HTTP for control, not local sockets

common/models/service.js, server/model-config.json, server/models/profile-data.js, test/meshctl-helper.js, test/test-instance-profiling.js
When ProfileData instance is deleted, also delete the profile file on
disk.
connected to strongloop-internal/scrum-nodeops#725
=> profile-data: support delete of ProfileData

bin/sl-meshctl.js, test/test-meshctl-env.js
URLs, such as those used by database connectors, often have = in them
and they should be preserved.
Closes #86
=> meshctl: preserve = in env var values

bin/sl-meshadm.js
connected to fix strongloop-internal/scrum-nodeops#804
=> meshadm: default command is exec-list

bin/sl-meshctl.js
Allows strong-pm and strong-central to be distinguished by the info
command.
connected to strongloop-internal/scrum-nodeops#805
=> meshctl: report server name in info output

bin/sl-meshctl.js
printServiceStatus() was being called in order of service ID, but since
it makes an async call to a REST API, the actual order of services
depended on the order in which the HTTP calls came back, which is
somewhat random.
=> meshctl: order status list by service ID

server/models/service-process.js, test/meshctl-helper.js, test/test-instance-profiling.js, test/test-service-external-db.js
New hooks were injected into the process update chain in f4cbe6a674ab1e3a96f24ef2b848238cc3ac29aa but the default implementations did not forward their results, breaking things.
=> fix regression in process hooks

bin/sl-meshadm.js, bin/sl-meshadm.txt, bin/sl-meshctl.txt
- Add usage docs for meshadm's support for ssh2 tunneling.
- Add SSH_PORT support for meshadm.
- Document ssh2 tunneling support for both meshctl and meshadm
Continuation of the contribution in #106 
@kraman PTAL
/cc @SemonCat
=> finish support for overriding the ssh port

bin/sl-meshctl.js, bin/sl-meshctl.txt, common/models/service-process.js, common/models/service-process.json, server/models/service-process.js, server/server.js, test/test-meshctl-debugger.js, test/test-meshctl-status.js, test/test-notification-model-updates.js
Add debugger control commands
- ServiceProcess:
- `startDebugger(cb)` at `POST /debugger/start`
- `stopDebugger(cb)` at `POST /debugger/stop`
- `bin/sl-meshctl`
- `dbg-start WRK`
- `dbg-stop WRK`
Intercept `debugger-status` notifications from strong-supervisor and update the property "ServiceProcess.debugger" with the debugger status.
Add a new per-worker column "Debugging" to sl-pmctl status output
See the [spike blog post](https://docs.google.com/document/d/1hPuuKQ3GCLKCUaQaNxuwyRqOfcI_tnqy5TLGLLdWHeM/edit) for a high-level architectural overview.
Connect to strongloop-internal/scrum-loopback#261
/to @kraman please review
/cc @sam-github
=> Debugger control channel

bin/sl-meshctl.js
Remove extra "undefined" string from the output (introduced by #109).
/cc @kraman FYI, I think this fix does not require a review.
=> sl-meshctl: fix stdout message on dbg-stop

server/model-config.json, server/models/instance-action.js
Instead of persisting them to disk and waiting for that persistence to
finish before handing back the result, just use the memory connector.
Furthermore, there isn't any reason to keep them around at all, so for
the immediate future we can use a simple 10s expiration so that the
instances can GC themselves instead of just accumulating in memory
indefinitely.
Connect to strongloop-internal/scrum-nodeops#908
Connect to strongloop-internal/scrum-nodeops#924
Connect to strongloop-internal/scrum-nodeops#961
Connect to strongloop-internal/scrum-nodeops#962
- This is meant as a short term solution with the eventual goal being to completely remove the InstanceAction model.
- This PR is against the 8.x branch and will need to be forward ported to master after merge.
=> make InstanceActions ephemeral

bin/sl-meshctl.js, test/test-client-version-mismatch.js, test/test-load-models.js, test/test-meshctl-cpu-profiling.js, test/test-meshctl-env.js, test/test-meshctl-heap-snapshot.js, test/test-meshctl-logdump.js, test/test-meshctl-npmls.js, test/test-meshctl-object-tracking.js, test/test-meshctl-patch.js, test/test-meshctl-restart.js, test/test-meshctl-ssh2.js, test/test-meshctl-start.js, test/test-meshctl-stop.js
* Use smarter assertions (`t.match(a, b)` vs `t.assert(b.test(a))`) for improved test debugging.
* Avoid `process.exit()` where possible to ensure stdio is flushed, allowing expected error messages to be seen
* Skip SSH based tests on Windows since it is unlikely to have sshd running locally
=> Make tests pass on Windows
