strongloop/strong-mesh-models

models/action.json
models/executor.js
models/executor.json
models/profile-data.json
models/service-instance.js
models/service-instance.json
models/service-metric.js
models/service-metric.json
models/service-process.js
package.json

Connect to strongloop-internal/scrum-nodeops#123

Add GUIDs and accessToken support

---

models/agent-trace.json
test/app/model-config.json

Connect to strongloop/strong-mesh-models#12

Add HTTP trace data model

---

common/models/express-usage-record.json
server/boot/extend-models.js
server/models/agent-trace.js
server/models/delete-old.js
server/models/express-usage-record.js
server/models/instance-action.js
server/models/server-service.js
server/models/service-instance.js
server/models/service-metric.js
server/models/service-process.js
server/server.js
test/test-notification-model-updates.js

Connect to strongloop/strong-pm#131

Factor out model updates and move them to mesh-models

---

test/helper.js
test/test-deploy-endpoints.js
test/test-instance-actions.js
test/test-instance-create-destroy.js
test/test-instance-profiling.js
test/test-notification-model-updates.js
test/test-service-create-destroy.js
test/test-service-env.js

Seeing collisions on CI from this.

test: listen on ephemeral port

---

client/client.js
common/models/executor.js
common/models/executor.json
common/models/service-process.js
package.json
server/models/service-process.js
server/server.js
test/meshctl-helper.js
test/test-notification-model-updates.js
test/test-trace-client-api.js
test/test-trace-disabled-client-api.js

Connect to strongloop-internal/scrum-nodeops#330
Connect to strongloop-internal/scrum-nodeops#332

concurix: use node IPC from tracer to pm for traces

---

bin/sl-meshctl.js
bin/sl-meshctl.txt
client/models/service-instance.js
test/test-meshctl-patch.js

Add patch command

---

server/models/service-process.js
test/test-trace-client-api.js

Connect to strongloop-internal/scrum-nodeops#331

Return decompressed traces

---

bin/sl-meshctl.js
common/models/express-usage-record.js
common/models/express-usage-record.json
mocks/mock-express-usage-record.js
server/datasources.local.js
server/models/delete-old.js
server/models/express-usage-record.js
server/models/service-process.js
server/server.js
test/test-express-usage-record.js
test/test-notification-model-updates.js
test/test-trace-client-api.js

Connect to strongloop-internal/scrum-nodeops#422

Add loopback metrics to express metrics api

---

client/client.js
common/models/express-usage-record.js
common/models/express-usage-record.json
mocks/mock-express-usage-record.js
server/models/express-usage-record.js
test/test-express-usage-record.js

Connect to strongloop/strong-arc#1188
/cc @anthonyettinger
/cc @altsang

Additional express-metrics updates

---

bin/sl-meshctl.js
test/meshctl-helper.js
test/test-meshctl-status.js

Connect to strongloop-internal/scrum-nodeops#507

list listening ports in status report

---

server/models/service-process.js

Required for docker support in strong-pm.

use process start time for real process upsert

---

bin/sl-meshctl.js
test/test-meshctl-cpu-profiling.js
test/test-meshctl-env.js
test/test-meshctl-heap-snapshot.js
test/test-meshctl-logdump.js
test/test-meshctl-npmls.js
test/test-meshctl-object-tracking.js
test/test-meshctl-patch.js
test/test-meshctl-restart.js
test/test-meshctl-set-size.js
test/test-meshctl-start.js
test/test-meshctl-stop.js

Connect to strongloop-internal/scrum-nodeops#517

ctl: mention URL in all error messages

---

bin/sl-meshctl.js
bin/sl-meshctl.txt
common/models/profile-data.json
common/models/service-process.json
server/boot/extend-models.js
server/models/instance-action.js
server/models/profile-data.js
server/models/server-service.js
server/models/service-process.js
server/server.js
test/test-meshctl-cpu-profiling.js

connected to strongloop-internal/scrum-nodeops#558

watchdog auto-stop support

---

package.json
server/server.js
test/meshctl-helper.js
test/test-trace-client-api.js

Connect to strongloop-internal/scrum-nodeops#563

Move Minkelite dependency to PM

---

bin/sl-meshctl.js
common/models/service-instance.js
common/models/service-instance.json
common/models/service-process.json
server/models/service-instance.js
server/models/service-process.js
server/server.js
test/test-meshctl-status.js
test/test-meshctl-tracing.js

Connect to strongloop-internal/scrum-nodeops#459

Add support to turn on/off tracing for an instance

---

.gitignore
server/models/instance-action.js
test/test-meshctl-cpu-profiling.js
test/test-meshctl-heap-snapshot.js

connected to strongloop-internal/scrum-nodeops#602

Profile send via ctl channel

---

bin/sl-meshctl.js
bin/sl-meshctl.txt
client/client.js

Connect to strongloop-internal/scrum-nodeops#627

Fix status and tracing commands

---

server/models/instance-action.js
server/models/server-service.js

connected to strongloop-internal/scrum-nodeops#635

Direct profile start as action

---

server/models/service-process.js

If multiple updates to the same process were happening concurrently
then the last handler to call `proc.save()` would overwrite the
changes made by the other handler. This is because `proc.save()` saves
the entire object instead of only updating the changed fields.
This manifested in listenening sockets being dropped randomly, as
reported in strongloop-internal/scrum-nodeops#639, because the
listening and status:wd events are sent at almost the same time and
are sometimes processed concurrently.
To reduce the problems caused by this, `proc.updateAttributes()` is
used wherever possible so that concurrent saves to different attributes
are at least safe.
Note that there is still a problem if multiple updates to the same
attributes happen concurrently. Fortunately, that does not tend to …

fix race condition in process update processing

---

server/models/service-instance.js
server/server.js
test/test-notification-model-updates.js

Connect to strongloop-internal/scrum-nodeops#665

Update instance appName based on status:wd msgs

---

bin/sl-meshadm.js
bin/sl-meshadm.txt
client/client.js
common/models/executor.js
common/models/executor.json
common/models/service-instance.json
index.js
package.json
server/auth.js
server/boot/extend-models.js
server/models/executor.js
server/models/server-service.js
server/models/service-instance.js
server/service-manager.js
test/test-deploy-endpoints.js
test/test-instance-create-destroy.js
test/test-meshctl-env.js
test/test-meshctl-set-size.js
test/test-service-create-destroy.js

Connect to strongloop-internal/scrum-nodeops#421

Model updates for strong-central

---

bin/sl-meshctl.js
server/service-manager.js
test/exec-meshctl.js
test/test-meshctl-set-size.js

I'd like to wait for after multiapp release to do this, I believe it may be related to, or at least occaisonally trigger, https://github.com/strongloop-internal/scrum-nodeops/issues/541
also, I need to fix the tests
depends on #45

Persist set size (WIP)

---

common/models/service-process.js
server/models/server-service.json
server/models/service-process.js

Add command for checking if a particular feature is available on the
process.
connect to strongloop-internal/scrum-nodeops#453

Query capabilities support

---

package.json
server/models/service-instance.js
server/models/service-process.js
test/test-notification-model-updates.js

Connect to strongloop-internal/scrum-nodeops#673

Update models to match supervisor notification updates

---

server/models/express-usage-record.js
server/models/instance-action.js
server/models/server-service.js
server/models/service-instance.js
server/models/service-process.js

Connect to strongloop-internal/scrum-nodeops#651

Catch missing model with LB find..() and relations

---

server/models/service-process.js
test/test-trace-client-api.js

Connect to strongloop-internal/scrum-nodeops#718

Trace api updated to use instanceId as hostname

---

bin/sl-meshadm.js
client/client.js
common/models/executor.js
server/models/executor.js
server/service-manager.js

connected to strongloop-internal/scrum-nodeops#672

meshadm: support executor-shutdown command

---

server/models/express-usage-record.js
test/test-express-usage-record.js

Fix URL parsing in express-metrics and reenable test

---

server/models/profile-data.js

Connect to strongloop-internal/scrum-nodeops#753

Fix process lookup for recording smart profile data

---

package.json
server/server.js
test/test-service-external-db.js

Connect to strongloop-internal/scrum-nodeops#409

Inject db configuration instead of datasource

---

server/models/server-service.js
server/models/service-instance.js

Connect to strongloop-internal/scrum-nodeops#677

Use updateAttributes instead of saving whole model

---

bin/sl-meshctl.txt

Connect to strongloop-internal/scrum-nodeops#776

Undoc SCALE option for service create

---

server/models/executor.js
server/service-manager.js

Connect to strongloop-internal/scrum-nodeops#800

Add executor destroy hooks

---

bin/sl-meshadm.js
bin/sl-meshadm.txt
client/client.js
client/model-config.json
common/models/gateway.json
server/boot/extend-models.js
server/model-config.json
server/models/gateway.js
server/models/service-process.js
server/service-manager.js
test/test-meshadm-exec.js
test/test-notification-model-updates.js

* Add gateway model and CRUD hooks
* Add gateway create/list/destroy Mesh Admin commands
* Add events to track process exit
Connect to strongloop-internal/scrum-nodeops#674

Add gateway support

---

common/models/gateway.json

Connect to strongloop-internal/scrum-nodeops#674

Use numeric IDs for gateway

---

bin/sl-meshctl.js

I'm not use port 22 for ssh on my server.

set ssh port when use http+ssh deploy via env

---

client/client.js
common/models/agent-trace.json
common/models/api.json
common/models/executor.json
common/models/express-usage-record.json
common/models/profile-data.json
common/models/service-instance.json
common/models/service-metric.json
common/models/service-process.json
common/models/service.json
server/models/executor.js
server/models/gateway.js
server/models/instance-action.js
server/models/observerHelper.js
server/models/server-service.js
server/models/service-instance.js
server/server.js
server/util.js
test/test-dbwatcher.js
test/test-meshadm-exec.js

connect to strongloop-internal/scrum-nodeops#899
connect to strongloop-internal/scrum-nodeops#949

Add DBWatcher support

---

bin/sl-meshctl.txt
client/client.js
client/models/server-service.js
server/models/service-process.js

* Switch from [svc].[exec].[pid] to [svc].[inst].[pid] in CLI

Change process display name use instance id

---

common/models/service.js
server/boot/observe-changes.js
server/middleware.json
server/models/executor.js
server/models/gateway.js
server/models/observerHelper.js
server/models/server-service.js
server/models/service-instance.js
test/test-instance-profiling.js
test/test-notification-model-updates.js

Connect to strongloop-internal/scrum-nodeops#945

Change streams to track instance/process changes
